[tool.poetry]
name = "hw8"
version = "0.1.0"
description = ""
authors = ["Delah0ya <viktor.deleichuk@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pymongo = {extras = ["srv"], version = "^4.6.1"}
python-dotenv = "^1.0.1"
redis = "^5.0.1"
redis-lru = "^0.1.2"
mongoengine = "^0.27.0"
pika = "^1.3.2"
mimesis = "^14.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
